#!groovy
import jenkins.scripts.script
@Library('amitdude') _

pipeline{
    agent any
    stages{
        stage("dude"){
            steps{
                deleteDir()
                
                checkout scm
                build()
                echo "dude 12"
            }
        }
    }
}