#!groovy
@Library('amitdude') _

pipeline{
    agent any

    parameters{
        choice(name: "version", choices: ['1.0.1','1.0.2','1.0.3'], description: 'choices for version')
        booleanParam(name: "checkflag", defaultValue: true)
    }    
     
    stages{
        stage("get repo and shared"){
            steps{
                deleteDir()
                
                checkout scm
                holyCrap()
                echo "dude 12"
            }
        }
        stage("build"){
            steps{
              if(checkflag) { 
                echo "build me"
              }
              else{
                  echo "kill me"
              }
            }
        }
        stage("deploy"){
            steps{
                echo "deply me"
            }
        }
    }
    post{
        success{
            echo "deply me"
        }
        always{
            echo "always me"
        }
        failure{
            echo "failure me"
        }
    }
}